# network/config/node3.toml
genesis-file="/config/genesis.json"
data-path="/var/lib/besu"

# Networking
p2p-enabled=true
p2p-port=30303

# JSON-RPC
rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]
rpc-http-api=["ETH","NET","WEB3","QBFT"]
host-allowlist=["*"]

# Logging
logging="INFO"
